thinkingPotatoes/FRONTEND

src/components/common/texts/Body1.js
src/components/common/texts/Body2.js
src/components/common/texts/Body3.js
src/components/common/texts/Caption1.js
src/components/common/texts/Caption2.js
src/components/common/texts/Head1.js
src/components/common/texts/Head2.js
src/components/common/texts/Head3.js
src/components/common/texts/Subtitle1.js
src/components/common/texts/Subtitle2.js
src/index.css

#23
텍스트 공통 컴포넌트 생성 및 색상 추가
- 텍스트 공통 컴포넌트 생성: 5f391719db000788ba5af38547507d05a7bb1e00
- 색상 추가: ca70b9ce1985ddcce484e4142230b5447e88a925

[#23] 텍스트 공통 컴포넌트 생성 및 색상 추가

---

src/App.tsx
src/router/index.tsx

#19 
로그인 여부에 따른 라우팅 기능을 추가하였습니다. 
라우팅 작업이라 별도의 스크린 샷은 없습니다.
Public(로그인 되어 있지 않은 사용자만 접근 가능한 페이지) : 로그인, 회원가입 페이지
Private(로그인 되어 있는 사용자만 접근 가능): 블로그, 리뷰 작성
Common(로그인 여부에 상관없이 접근 가능한 페이지): Home, Search, ReviewDetail
위와 같이 로그인 여부에 따라 라우팅이 될 수 있도록 구분해두었습니다. 수정이 필요하거나 더 나은 방식이 있으시면 의견 주시면 좋을 것 같습니다!
close #19

[#19] 라우팅 기능 추가

---

dockerfile

#48 
배포를 위한 도커파일 추가
- [9d976c](https://github.com/thinkingPotatoes/FRONTEND/commit/9d976c224108bc275294634902303bf0869df2e3)
close #48

[#48] 도커 파일 추가

---

src/components/common/Footer.tsx
src/components/movieSearch/ReviewList.tsx
src/components/selectMovie/SearchResult.tsx
src/pages/PostReview.tsx
src/pages/PostReviewOption.tsx
src/pages/PostReviewRequired.tsx
src/router/index.tsx

#54 
review 작성 path postreview로 변경 (review 상세와 겹침)
- review 작성 path postreview로 변경: d1256b9729f4068280ab27d96f5950abaabcda03
close #54

[#54] review 작성 path postreview로 변경 (review 상세와 겹침)

---

src/pages/Login.tsx
src/router/index.tsx

#65 
소셜 로그인 기능 구현
X
소셜 로그인 버튼에 기능 연결
로그인 시도시 아직 Redirect가 정상적으로 되지 않아서 로그인 이후의 accessToken 세팅 등이 기능 구현 필요
close #65

[#65] feat: 소셜 로그인 기능 구현

---

src/components/home/HotReviewDetail.tsx
src/components/home/HotReviewItem.tsx
src/components/home/HotReviewList.tsx
src/index.css
src/pages/Home.tsx
src/pages/Login.tsx

#68 
- 비로그인 기능 추가
- 핫한 리뷰 기능 추가

[#68] 홈화면 추가 기능 구현 추가

---

src/components/blog/BlogReviewCalendar.tsx
src/components/blog/BlogReviewModalItem.tsx
src/components/blog/BlogReviewSummaryItem.tsx
src/types/review.ts

#59 
Filog 달력에서 날짜를 선택시 작성할 리뷰를 볼 수 있는 기능 구현

[#59] 달력에서 날짜 선택시 리뷰를 볼 수 있는 기능 구현

---

src/pages/Setting-page/MyInfo/SelectJanre.tsx

#70 
장르 선택 페이지 db 조회 api 연결
- 제 pc 에서 장르 추가가 안되어서 우선 노션 참고하여 연결해뒀습니다 
장르 선택 페이지 db 조회 api 연결
close #70

[#70] feat: 장르 선택 페이지 db 조회 api 연결

---

tsconfig.json

unused value 에러 수정
#72 
빌드 에러 수정
X
declared unused value 에러를 잡지 않도록 수정
close #72

[#72] 빌드 에러 수정

---

dockerfile
src/api/apiController.tsx
src/pages/LoginPassword.tsx
src/pages/Redirect.tsx

#75 
포트 번호 변경
- 포트 번호 변경: c4dbb7e2b365ee62227176f992c6c99d4c62ee8f
close #75

[#75] 포트 번호 변경

---

src/pages/Blog.tsx

[#78] feat: 블로그 정보 api call

---

src/pages/Blog.tsx

#81 
장르 목록 null일 경우 optional chaining으로 처리
close #81

[#81] fix: 장르 목록 null일 경우 optional chaining으로 처리

---

src/components/blog/SettingIcon.tsx
src/pages/Blog.tsx

[#81] fix: 제목, 칩 없을 때 setting icon 위치 깨지는 것 수정

---

src/pages/Blog.tsx

[#81] fix: dto 변경

---

src/components/blog/BlogReviewList.tsx
src/components/blog/BlogReviewSection.tsx
src/components/common/Footer.tsx
src/components/movieSearch/MovieInfo.tsx
src/pages/Blog.tsx
src/pages/PostReviewOption.tsx

#88 
QA 수정사항 반영
- 리뷰 작성 완료 후 홈 화면으로 navigate
- 누구님의 영화리뷰 -> 닉네임 반영
- 영화 상세 더보기 스크롤
close #88

[#88] fix: QA 수정사항 반영

---

src/components/home/HotReviewItem.tsx
src/components/movieSearch/MovieInfo.tsx
src/pages/PostReviewOption.tsx

#88 
QA 수정사항 추가 반영
- 리뷰 작성 완료 후 블로그 화면으로 이동
- 지금 핫한 리뷰 별점 수정되지 않도록 변경

[#88] fix: QA 수정사항 추가 반영

---

src/pages/RegisterSuccess.tsx

#94 
화면이 작은 경우 버튼이 바로 보이도록 sticky 하게 수정
화면이 작은 경우 버튼이 바로 보이지 않아 혼란을 주어서 버튼 영역을 sticky 하게 수정
close #94

[#94] fix: 회원가입 완료 페이지 버튼 위치 수정

---

src/router/index.tsx

#97 
이메일 인증시 페이지가 뜨지 않는 오류 수정
이메일 인증 리다이렉트 페이지가 연결되어 있지 않아서 연결하도록 수정
close #97

[#97] fix : 이메일 인증시 페이지가 뜨지 않는 오류 수정

---

src/pages/RegisterSuccess.tsx
src/router/index.tsx

Develop to Master

---

src/components/common/CommentCount.tsx
src/components/common/LikeCount.tsx
src/components/home/Header.tsx
src/components/home/HotReviewItem.tsx
src/components/home/HotReviewList.tsx
src/pages/MovieTasteSelection.tsx

#100 
- 팝콘 아이콘 제거
- 검색 아이콘 크기 수정
- 핫한 리뷰 하단 패딩 추가
- 지금 핫한 리뷰 UI 수정
- 영화 선택 버튼 sticky하게 수정
close #100

Feature#100
